# This is a basic workflow to help you get started with Actions

name: SSH

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: mdelillo/ssh-server-action@v1
      with:
        ngrok-authtoken: "5ZLNf619ZYd16QsdnysMX_FWUHDEvCjx4v6yRVJZ8q"
        ssh-public-key: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAz8QmU2uEyYgO8DtKkoEghB6q//iiVj1xmcBhN/qqszbJFk5u1nQO8rJ+hqoSJJgtepZvILfOCpqDAYwJMCr9ExmVhSNNsNAjOfn90oeaRQt+t/cQbpf8DwsZHUNzsfKZaBCjZlv1pwXBbwUcSF6E0uiSEvjnhYRGV6B547/G+KsehuU2N4ZyxpVvYpjrTlyIWc2efV2TY30pLQbrQkPQwVnQrC0Q+XgnXKK3x/bPLx2zYnZ4fNvui9/ngXaYAa1+LroRlUQaWzR0t0OSWseqnq3sVhSZNhqLjCfvJtP8/A5+QfbBe1PZ5tkyz/JbCGCpbKK7dQGyk3naaHEFP0a/qw=="
